# Generated by Django 2.2.4 on 2019-09-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnm',
            name='closed_one',
            field=models.BooleanField(blank=True, null=True, verbose_name='Closed Recruitment One'),
        ),
        migrations.AlterField(
            model_name='pnm',
            name='closed_three',
            field=models.BooleanField(blank=True, null=True, verbose_name='Closed Recruitment Three'),
        ),
        migrations.AlterField(
            model_name='pnm',
            name='closed_two',
            field=models.BooleanField(blank=True, null=True, verbose_name='Closed Recruitment Two'),
        ),
        migrations.AlterField(
            model_name='pnm',
            name='open_friday',
            field=models.BooleanField(blank=True, null=True, verbose_name='Open Recruitment Friday'),
        ),
        migrations.AlterField(
            model_name='pnm',
            name='open_one',
            field=models.BooleanField(blank=True, null=True, verbose_name='Open Recruitment One'),
        ),
        migrations.AlterField(
            model_name='pnm',
            name='open_three',
            field=models.BooleanField(blank=True, null=True, verbose_name='Open Recruitment Three'),
        ),
        migrations.AlterField(
            model_name='pnm',
            name='open_two',
            field=models.BooleanField(blank=True, null=True, verbose_name='Open Recruitment Two'),
        ),
        migrations.AlterField(
            model_name='pnm',
            name='potluck',
            field=models.BooleanField(blank=True, null=True, verbose_name='Potluck'),
        ),
    ]
