# Generated by Django 2.2.5 on 2019-09-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_auto_20190909_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnm',
            name='fact_sheet',
            field=models.BooleanField(blank=True, null=True, verbose_name='Fact Sheet'),
        ),
        migrations.AddField(
            model_name='pnm',
            name='ipanel_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='IPanel Order Number'),
        ),
    ]
