# Generated by Django 2.2.4 on 2019-08-25 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_auto_20190821_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='sibling',
            name='pledge_class',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Pledge Class'),
        ),
        migrations.AlterField(
            model_name='sibling',
            name='big',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkin.Sibling', verbose_name='Big (Currently Active)'),
        ),
        migrations.AlterField(
            model_name='sibling',
            name='big_alumni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkin.Alumni', verbose_name='Big (Alumni)'),
        ),
        migrations.AlterField(
            model_name='sibling',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='sibling',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='sibling',
            name='house',
            field=models.CharField(blank=True, choices=[('Rollawood', 'Rollawood'), ('Torchia', 'Torchia'), ('Harryhill', 'Harryhill'), ('', '')], max_length=10, null=True, verbose_name='House'),
        ),
        migrations.AlterField(
            model_name='sibling',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='sibling',
            name='onyen',
            field=models.CharField(max_length=20, unique=True, verbose_name='Onyen'),
        ),
        migrations.AlterField(
            model_name='sibling',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active')], max_length=20, null=True, verbose_name='Status'),
        ),
    ]
