# Generated by Django 2.2.4 on 2019-08-25 21:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_auto_20190825_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date and Time'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.Event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='sibling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.Sibling', verbose_name='Sibling'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(verbose_name='Date and Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.EventType', verbose_name='Event Type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='unique_id',
            field=models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Event Code'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='gpatracker',
            name='gpa',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='GPA'),
        ),
        migrations.AlterField(
            model_name='gpatracker',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='gpatracker',
            name='sibling',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='checkin.Sibling', verbose_name='Sibling'),
        ),
    ]
