# Generated by Django 2.2.4 on 2019-08-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0004_auto_20190825_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sibling',
            name='house',
            field=models.CharField(blank=True, choices=[('Rollawood', 'Rollawood'), ('Torchia', 'Torchia'), ('Harryhill', 'Harryhill'), ('Bigelow', 'Bigelow')], max_length=10, null=True, verbose_name='House'),
        ),
    ]
