# Generated by Django 2.2.5 on 2019-09-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0006_auto_20190908_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='sibling',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='sibling',
            name='preferred_contact',
            field=models.CharField(blank=True, choices=[('Text', 'Text'), ('Email', 'Email')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sibling',
            name='pronouns',
            field=models.CharField(blank=True, choices=[('he/him/his', 'he/him/his'), ('she/her/hers', 'she/her/hers'), ('they/them/theirs', 'they/them/theirs')], max_length=20, null=True, verbose_name='Pronouns'),
        ),
    ]
