# Generated by Django 2.2.4 on 2019-09-13 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPanelAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onyen', models.CharField(max_length=20, unique=True, verbose_name='Onyen')),
                ('passcode', models.CharField(max_length=20, unique=True, verbose_name='Passcode')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnm_number', models.IntegerField(verbose_name='PNM Number')),
                ('vote', models.CharField(choices=[('Y', 'Yes'), ('No', 'No'), ('A', 'Abstain')], default='A', max_length=10)),
                ('vote_onyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipanel.IPanelAuth', verbose_name='Vote Onyen')),
            ],
        ),
    ]
