# Generated by Django 2.2.4 on 2019-09-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('A', 'Abstain')], default='A', max_length=10),
        ),
    ]
