# Generated by Django 2.2.5 on 2019-09-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipanel', '0003_pnmipanel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnmipanel',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pnmipanel',
            name='status',
            field=models.CharField(choices=[('L', 'Locked'), ('O', 'Open')], max_length=10, verbose_name='Status'),
        ),
    ]
