# Generated by Django 2.2.5 on 2019-09-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipanel', '0004_auto_20190920_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnmipanel',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='Number'),
        ),
    ]
